### ISSUE TITLE
Error with language pack 

### ISSUE THREAD

**Issue by Asgoret** [spring-projects/atom-concourse#4]
Hi!

I install atom plugin via atom settings and catch strange error in *Outline* view.
![image](https://user-images.githubusercontent.com/30697011/43004186-ad276784-8c37-11e8-8fe3-2182cc685d08.png)
How can i fix it? Reinstall isn`t help me.

**Comment by BoykoAlex** [comment]
Hmm... that works for me with the latest 0.4.0... Is that the version you have installed? Which version of Atom do you have? Do you get hovers and content assist in the editor? Is the only thing not working being the outline content? Did you try hiding it and then opening the outline view again?
Also try opening dev tools (View -> Developer -> Toggle Developer Tools). See what's the console. The console should show comm messages between atom and LS process. One of the messages around the bottom should be:
`Concourse-Pipeline-YAML (Concourse-Pipeline-YAML) rpc.sendRequest textDocument/documentSymbol`
Check what are the contents of the message. It should have the content for the outline view

**Comment by Asgoret** [comment]
@BoykoAlex Hi!
My Atom version is 1.27.1. From setting i have 0.4.0 version of plugin. 
No, i haven't got any problems in editor. 
How can i check Outline? I don't use it before). And yes i tried to hide\reload view and atom.

hhhmmm....it's very strange, but i haven't got any messages from `concourse` in developer toogle. can it be wrong installation or i missed some packages?

**Comment by Asgoret** [comment]
@BoykoAlex  Ok....It work now, but very odd.
For example, i must add folder with pipeline like a project, without that Outline doesn't work.
But, Outline not for all files from tutorial
![image](https://user-images.githubusercontent.com/30697011/43034510-6ee1f3a4-8ce6-11e8-8fbf-1cf2e1db0831.png)

 Green files work fine and orange or not colored files doesn't work(((

UPD: And you must delete last empty row or outline doesn't work for green file.

**Comment by Asgoret** [comment]
Orange file
![image](https://user-images.githubusercontent.com/30697011/43034522-9c0eddb0-8ce6-11e8-9df9-59295bf6e2da.png)

Green file
![image](https://user-images.githubusercontent.com/30697011/43034535-cede4ab4-8ce6-11e8-841d-539ebd56cf72.png)

**Comment by Asgoret** [comment]
Work
![image](https://user-images.githubusercontent.com/30697011/43034750-e7e92cb4-8cea-11e8-9cda-8d7cd820db9a.png)

Don't work
![image](https://user-images.githubusercontent.com/30697011/43034755-13629c5e-8ceb-11e8-9bb7-9b6c99bd6cac.png)

**Comment by BoykoAlex** [comment]
Atom's outline works with only one outline provider. Probably the latest provider's content is being displayed. Do you have 'ide-yaml` package installed?
If you switch between grammars, i.e. `YAML` and `Concourse-Task-YAML` the outline view won't automatically refresh itself. You'd have to type something to refresh the outline.

Now, `Concourse-Task-YAML` doesn't have an outline, not supported the LS. `Concourse-Pipeline-YAML` outline is supported by the LS.

The outline that you see for the pipeline file is not coming from the Concourse LS. I'll paste you how it looks below:
<img width="1111" alt="screen shot 2018-07-22 at 17 35 50" src="https://user-images.githubusercontent.com/6433390/43050384-c25761d2-8dd5-11e8-9754-f2d95c897139.png">

The Outline view sometimes seem to be stuck. If you see that "blue spinning circle" for a while close the view and reooen it.

**Comment by BoykoAlex** [comment]
Looks like if the Outline view is opened and a new pipeline or task file is opened then you get a spinning circle in the outline. This is a bug in the atom language client. This should trigger `textDocument/documentSymbol` request ones LS initializes and Outline view is opened. Raised: https://github.com/atom/atom-languageclient/issues/229

**Comment by Asgoret** [comment]
Since it's error somewhere in atom. Close issue.
