### ISSUE TITLE
Invalid registry type for a valid registry type?

### ISSUE THREAD

**Issue by jkamenik** [spring-projects/atom-concourse#7]
I am getting the following error

```
The 'registry-image' Resource Type does not exist.  Existing types: [debug, git, hg, time, s3, archive, semver, github-release, docker-image, tracker, pool, cf, bosh-io-release, bosh-io.stemcell, bosh-deployment, vagrant-cloud]
```

However, it is found in the underlying [sts4 repo](https://github.com/spring-projects/sts4/blob/d1d90feb8cfae6de3731e4ca5512c431fdb5eb4c/headless-services/concourse-language-server/src/main/java/org/springframework/ide/vscode/concourse/PipelineYmlSchema.java#L79).

Does the dependency need to be updated and this package rebuilt?

**Comment by BoykoAlex** [comment]
@jkamenik we stopped supporting Atom... Its language client lib doesn't evolve as we need it to. We only support Eclipse, VSCode and Theia at the moment.
Perhaps we'll be able to release a new concourse atom package if you really need it. Thus the new LS from the repo head would be in it

**Comment by jkamenik** [comment]
Thanks it would be great if you could / push a new package so my Atom sees the change.  Thanks.

**Comment by BoykoAlex** [comment]
Alright, we are having a release next week. I'll publish atom extensions silently but will post here when new atom extensions are available.

**Comment by BoykoAlex** [comment]
`atom-concourse` 1.13.0 is published please give it a try.
Also, I recalled that you can sort of install atom extension straight from the git repo such as this one. In other words you wouldn't need to wait for us to release anything. Instructions are in the README.md of the repo namely this piece: https://github.com/spring-projects/atom-concourse#releases (the 6 steps below to try dev snapshot)

**Comment by jkamenik** [comment]
Thanks Alex.  Installed and is working.
